/**
 * @file    AppInclude.jsx
 *
 * @author  Emma Natalie Soh
 * @par     Email: 2202191\@sit.singaporetech.edu.sg
 * @par     Course: CSD3156 Mobile and Cloud Computing
 * @par     Project: Cloud Computing Project
 *
 * @brief   This file declares the constants.
 *
 * This file will be autogenerated on boot-up by the EC2 instance.
 * This is simply a sample of what is inside.
 */

export const PHP_URL = "http://50.17.11.14/";
