<?php

/**
 * @file    EC2MetadataInclude.php
 * @author  Emma Natalie Soh
 * @par     Email: 2202191\@sit.singaporetech.edu.sg
 * @par     Course: CSD3156 Mobile and Cloud Computing
 * @par     Project: Cloud Computing Project
 *
 * @brief   This file declares constants for the metadata for the EC2 instance.
 *
 * This file will be autogenerated in the EC2 instance.
 */

/**
 * The current EC2 Instance ID for the PHP server.
 */
define('EC2_INSTANCE_ID', 'UNKNOWN_INSTANCE');

/**
 * The current EC2 Instance's private IP for the PHP server.
 */
define('EC2_PRIVATE_IP', 'UNKNOWN_PRIVATE_IP');

/**
 * The current EC2 Instance public IP for the PHP server.
 */
define('EC2_PUBLIC_IP', 'UNKNOWN_PUBLIC_IP');

/**
 * The current EC2 Instance's instance type for the PHP public server..
 */
define('EC2_INSTANCE_TYPE', 'UNKNOWN_TYPE');

/**
 * The current EC2 Instance's availability zone for the PHP public server.
 */
define('EC2_AVAILABILITY_ZONE', 'UNKNOWN_ZONE');
